export const dynamic = 'force-dynamic';

/**
 * Pricing API
 * GET: Get current pricing for all actions
 */

import { NextRequest, NextResponse } from 'next/server';

const PRICING = {
  api_call: {
    name: 'API Call',
    description: 'Each API request to agent services',
    unitCost: 0.001,
    unit: 'call',
    model: 'per_call',
    example: '1000 calls = $1.00',
  },
  token_input: {
    name: 'Input Token',
    description: 'Tokens sent to AI models (prompts)',
    unitCost: 0.0001,
    unit: 'token',
    model: 'per_token',
    example: '10,000 tokens = $1.00',
  },
  token_output: {
    name: 'Output Token',
    description: 'Tokens generated by AI models (responses)',
    unitCost: 0.0002,
    unit: 'token',
    model: 'per_token',
    example: '5,000 tokens = $1.00',
  },
  compute_second: {
    name: 'Compute Time',
    description: 'Processing time on compute nodes',
    unitCost: 0.000167,
    unit: 'second',
    model: 'per_second',
    example: '60 minutes = $0.60',
  },
  task_completed: {
    name: 'Task Completed',
    description: 'Successfully completed task outcome',
    unitCost: 0.05,
    unit: 'task',
    model: 'outcome_based',
    example: '20 tasks = $1.00',
  },
  task_failed: {
    name: 'Task Failed',
    description: 'Failed task (minimal charge for compute used)',
    unitCost: 0.005,
    unit: 'task',
    model: 'outcome_based',
    example: '200 failed tasks = $1.00',
  },
  storage_gb: {
    name: 'Storage',
    description: 'Data storage per GB per month',
    unitCost: 0.023,
    unit: 'gb',
    model: 'per_second',
    example: '1 GB for 30 days = $0.023',
  },
  bandwidth_gb: {
    name: 'Bandwidth',
    description: 'Data transfer egress',
    unitCost: 0.09,
    unit: 'gb',
    model: 'per_call',
    example: '10 GB = $0.90',
  },
  websocket_connection: {
    name: 'WebSocket Connection',
    description: 'Real-time connection per minute',
    unitCost: 0.0001,
    unit: 'minute',
    model: 'per_second',
    example: '10,000 minutes = $1.00',
  },
};

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const action = searchParams.get('action');
    
    if (action) {
      const pricing = PRICING[action as keyof typeof PRICING];
      if (!pricing) {
        return NextResponse.json(
          { error: 'Invalid action', validActions: Object.keys(PRICING) },
          { status: 404 }
        );
      }
      return NextResponse.json({ success: true, action, pricing });
    }
    
    return NextResponse.json({
      success: true,
      pricing: PRICING,
      note: 'All prices in USD. No hidden fees. No minimums.',
    });
    
  } catch (error: any) {
    console.error('[Pricing API] Error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to get pricing', code: 'PRICING_ERROR' },
      { status: 500 }
    );
  }
}